export enum SolarUnitStatus {
    ACTIVE = "ACTIVE",
    INACTIVE = "INACTIVE",
    MAINTENANCE = "MAINTENANCE",
}

export enum AnomalyType {
    ZERO_GENERATION = "ZERO_GENERATION",
    SUDDEN_DROP = "SUDDEN_DROP",
    ERRATIC_FLUCTUATION = "ERRATIC_FLUCTUATION",
    PERFORMANCE_DEGRADATION = "PERFORMANCE_DEGRADATION",
    INVERTER_OFFLINE = "INVERTER_OFFLINE",
    PANEL_SHADING = "PANEL_SHADING",
    GRID_INSTABILITY = "GRID_INSTABILITY",
    TEMPERATURE_OVERHEAT = "TEMPERATURE_OVERHEAT",
}

export enum AnomalySeverity {
    CRITICAL = "CRITICAL",
    WARNING = "WARNING",
    INFO = "INFO",
}

export enum AnomalyStatus {
    NEW = "NEW",
    ACKNOWLEDGED = "ACKNOWLEDGED",
    RESOLVED = "RESOLVED",
}

export enum PaymentStatus {
    PAID = "PAID",
    PENDING = "PENDING",
    OVERDUE = "OVERDUE",
    FAILED = "FAILED",
}

export const SYSTEM_CONSTANTS = {
    DEFAULT_PAGE_SIZE: 10,
    MAX_PAGE_SIZE: 100,
    SYNC_BATCH_SIZE: 1000,
};
